server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/ # prefix는 컨트롤러가 리턴할 때 앞에 붙여주는 경로명 / suffix는 뒤
      suffix: .jsp
#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: 123qwe@@
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 나중에는 update로 바꿔야 기존 data가 안 지워진다. create는 매번 실행할때마다 table를 다시 만들어준다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # table(Entity)를 만들 떄 변수명 !그대로 넣어준다.
      use-new-id-generator-mappings: false #JPA의 기본 넘버링 전략을 따라가지 않겠다.
    show-sql: true # 이게 있어야 console창에 보인다.
    properties:
      hibernate.format_sql: true # console창에 보일 때 정렬에서 보여줌.

  jackson:
    serialization:
      fail-on-empty-beans: false
      
      
      